# permissions for end users to view templatesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatesecret-viewer-role
rules:
- apiGroups:
  - addem.se
  resources:
  - templatesecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addem.se
  resources:
  - templatesecrets/status
  verbs:
  - get
