# permissions for end users to edit templatesecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatesecret-editor-role
rules:
- apiGroups:
  - addem.se
  resources:
  - templatesecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addem.se
  resources:
  - templatesecrets/status
  verbs:
  - get
