apiVersion: addem.se/v1alpha1
kind: TemplateSecret
metadata:
  name: templatesecret-sample
spec:
  secretName: templatesecret-sample
  template:
    inline:
      "alertmanager.yaml": |
        global:
          resolve_timeout: 5m
        slack_api_url: "%SLACK_API_URL%"
  replacements:
    - match:
        exact: "%SLACK_API_URL%"
      replacement:
        secretKeyRef:
          name: slack-api-url
          key: url
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-api-url
stringData:
  url: https://api.slack.com/123abc
